### ISSUE TITLE
Expressing my graditude for your existance

### ISSUE THREAD

**Issue by gustxyz** [kenshaw/baseconv#3]
Hey Kieth, 

Just wanted to leave you a message in a semi-personalized way to thank you for your talk at GoJakarta on using Go with WASM (https://www.youtube.com/watch?v=Xp53ln1nFuk&t=1327s). 

You've inspired a green jr PHP/NODE web engineer looking for a language change and a new career specialization to put all of his chips into GO and to start experimenting with WASM. I've been using GO for 3 days and and am a complete zealot for this language now(I'm driving my dev team mad), and I have your video to thank. I can't wait to see whats in store for GO and/or WASM... and I want to be a part of it.

Thank you!

chzStatus, err := Cheeseyness("End")
if err != nil {
    fmt.Println(err)
}

**Comment by kenshaw** [comment]
Thanks! Glad someone could find it useful!
